- name: install and run ngnix
  hosts: web
  become: yes # -b
  tasks:
  - name: install ngnix
    ansible.builtin.package:
      name: ngnix
      state: present
  - name: start the ngnix
    ansible.builtin.service:
      name: ngnix
      state: started
      enabled: yes


