- name: variables
  hosts: local
  connection: local
  vars: # PLAY level variable, global variable
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: Sivakumar
  tasks:
    - name: print the variables
      vars: # Taks level variable, local variable
        COURSE: Ansible
      ansible.buildin.debug:
        msg: "Course is {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"

    - name: print the variables1
      ansible.buildin.debug:
        msg: "Course is {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"
